### PR TITLE
Update collect.py

### PR DESCRIPTION
**Pull request by pjhaynes1**
Webdriver request for MacOS, line 115

### CODE REVIEW

**Comment by sertalpbilal** [comment]
Hi Phil, sorry that I missed your merge request! Will be merging it soon.

**Comment by sertalpbilal** [comment]
Do you need to pass an executable path or does it work as is?

**Comment by pjhaynes1** [comment]
Hi Sertalp, great work! Not a problem, it works as is, driver installed via brew cask. 

To make it Darwin friendly I had to modify the shutil block's platform and directories accordingly (~line 170). To something like: 
` if platform == "darwin":
        shutil.move((os.path.expanduser("~/Downloads/fplreview.csv")), target_folder / f"fplreview-{page}.csv")`

_Nb._ Upon running I had to comment freezeall in run.py (line 10).

**Comment by sertalpbilal** [comment]
Thanks a lot!

**Comment by pjhaynes1** [comment]
I have since made a pull request for the Darwin shutil block - it wasn't in my initial commit.

**Comment by sertalpbilal** [comment]
Can you create another pull request?

**Pull request merged**
